name : CI

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-central-1'

  push:
    branches:
      - main

name: Deploy

jobs:
  # amplify:
  #   name: Deploy to Amplify Console
  #   runs-on: ubuntu-latest
  #   outputs:
  #     env-name: ${{ steps.env-name.outputs.environment }}
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

    # # Configure les infos d'identification d'AWS pour GitHub Actions
    # - name: Configure AWS credentials
    #   id: creds
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ github.event.inputs.region }}

    # - name: Configure environment name
    #   id: env-name
    #   env:
    #     REPO: ${{ github.repository }}
    #   run: |
    #     ENVIRONMENT=`echo $REPO | tr "/" "-"`
    #     echo "Environment name: $ENVIRONMENT"
    #     echo "::set-output name=environment::$ENVIRONMENT"
    
    buildx:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Set up Docker buildx
          id : buildx
          uses: docker/setup-buildx-action@v1
          with:
            install: true
        - 
          name: Inspect builder
          run: |
            echo "Name: ${{ steps.buildx.outputs.name }}"
            echo "Endpoint: ${{ steps.buildx.outputs.endpoint }}"
            echo "Status: ${{ steps.buildx.outputs.status }}"
        -
          name: Build
          run: |
            docker build .
    # # When a domain is configured to the stack,
    # # it gets configured in the environment and printed to the console.
    # - name: Print default domain
    #   env:
    #     DefaultDomain: ${{ steps.amplify-stack.outputs.DefaultDomain }}
    #   run: |
    #     echo "Default Domain: $DefaultDomain"